<?php

namespace AppBundle\Repository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends \Doctrine\ORM\EntityRepository {

	// Busca N comentarios de la noticia comenzando desde el offset inicio
	public function buscarListaN($noticia, $inicio, $N) { 

        $qb = $this->createQueryBuilder('c'); 
        $qb->leftJoin('c.noticia', 'n') 
        	->where($qb->expr()->eq('n.id', '?1')) // ya se puede utilizar ms directamente
            ->setParameter(1, $noticia->getId()) // sólo queremos la noticia pasada como parámetro a la función
			->addOrderBy('c.fecha', 'DESC')
			->setFirstResult($inicio) // offset (número de noticia) a partir del cual vamos a devolver
			->setMaxResults($N) // cantidad de comentarios que se vana devolver
		;
      
		$comentarios = $qb->getQuery()->getResult(); 
		return $comentarios; 
	}	
}
