<?php

namespace AppBundle\Repository;

/**
 * VisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaRepository extends \Doctrine\ORM\EntityRepository {

	// Crea la nueva visita en la BD
	public function insertar($em, $visita) {

        $em->persist($visita);
        $em->flush();
	}

	// Busca la vista de una fecha dada
	public function buscarFecha($fecha) {
		$visita = $this->findOneByFecha($fecha);
		return $visita;
	}		
}

